// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DevSpot.Copilot.AcceptanceTests.Features.JobPosting
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "seed:roles")]
    [global::Xunit.TraitAttribute("Category", "seed:users")]
    public partial class GestioneAnnunciDiLavoroFeature : object, global::Xunit.IClassFixture<GestioneAnnunciDiLavoroFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "seed:roles",
                "seed:users"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("it"), "Features/JobPosting", "Gestione annunci di lavoro", "  In qualità di datore di lavoro\n  Voglio creare e visualizzare gli annunci di la" +
                "voro\n  Così che le nuove posizioni rimangano salvate", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateJobPosting.feature"
#line hidden
        
        public GestioneAnnunciDiLavoroFeature(GestioneAnnunciDiLavoroFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/JobPosting/CreateJobPosting.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Gli utenti anonimi vengono reindirizzati lontano dalla pagina di creazione")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gestione annunci di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Gli utenti anonimi vengono reindirizzati lontano dalla pagina di creazione")]
        [global::Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async global::System.Threading.Tasks.Task GliUtentiAnonimiVengonoReindirizzatiLontanoDallaPaginaDiCreazione()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:anonymous"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Gli utenti anonimi vengono reindirizzati lontano dalla pagina di creazione", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
    await testRunner.GivenAsync("che sono sulla pagina \"Nuovo annuncio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 11
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Accesso\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="I campi mancanti di un annuncio mostrano gli errori di convalida")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gestione annunci di lavoro")]
        [global::Xunit.TraitAttribute("Description", "I campi mancanti di un annuncio mostrano gli errori di convalida")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task ICampiMancantiDiUnAnnuncioMostranoGliErroriDiConvalida()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("I campi mancanti di un annuncio mostrano gli errori di convalida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("che sono sulla pagina \"Nuovo annuncio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 16
    await testRunner.WhenAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("dovrei vedere il messaggio di convalida \"Il campo Title è obbligatorio.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 18
    await testRunner.AndAsync("dovrei vedere il messaggio di convalida \"Il campo Description è obbligatorio.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 19
    await testRunner.AndAsync("dovrei vedere il messaggio di convalida \"Il campo Company è obbligatorio.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 20
    await testRunner.AndAsync("dovrei vedere il messaggio di convalida \"Il campo Location è obbligatorio.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Un datore di lavoro può creare un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Gestione annunci di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Un datore di lavoro può creare un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task UnDatoreDiLavoroPuoCreareUnAnnuncioDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un datore di lavoro può creare un annuncio di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("che sono sulla pagina \"Nuovo annuncio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table1.AddRow(new string[] {
                            "Title",
                            "Backend Engineer"});
                table1.AddRow(new string[] {
                            "Description",
                            "Build services"});
                table1.AddRow(new string[] {
                            "Company",
                            "DevSpot"});
                table1.AddRow(new string[] {
                            "Location",
                            "Remote"});
#line 25
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori", ((string)(null)), table1, "Quando ");
#line hidden
#line 31
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 32
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Tutti gli annunci\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 33
    await testRunner.WhenAsync("seguo il reindirizzamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 34
    await testRunner.ThenAsync("dovrei vedere \"Backend Engineer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 35
    await testRunner.AndAsync("il database dovrebbe contenere un annuncio di lavoro intitolato \"Backend Engineer" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GestioneAnnunciDiLavoroFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GestioneAnnunciDiLavoroFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
