// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DevSpot.Copilot.AcceptanceTests.Features.JobPosting
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "seed:roles")]
    [global::Xunit.TraitAttribute("Category", "seed:users")]
    public partial class CoperturaVisualizzazioneOfferteDiLavoroFeature : object, global::Xunit.IClassFixture<CoperturaVisualizzazioneOfferteDiLavoroFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "seed:roles",
                "seed:users"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("it"), "Features/JobPosting", "Copertura visualizzazione offerte di lavoro", "  In qualità di visitatore o utente autenticato\n  Voglio visualizzare le offerte " +
                "di lavoro in base ai miei permessi di accesso\n  Così da consultare gli annunci s" +
                "enza ricevere errori", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "JobPostingVisibilityCoverage.feature"
#line hidden
        
        public CoperturaVisualizzazioneOfferteDiLavoroFeature(CoperturaVisualizzazioneOfferteDiLavoroFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/JobPosting/JobPostingVisibilityCoverage.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Un visitatore anonimo visualizza tutte le offerte di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Copertura visualizzazione offerte di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Un visitatore anonimo visualizza tutte le offerte di lavoro")]
        public async global::System.Threading.Tasks.Task UnVisitatoreAnonimoVisualizzaTutteLeOfferteDiLavoro()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un visitatore anonimo visualizza tutte le offerte di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("che sono sulla pagina \"Offerte di lavoro\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 10
    await testRunner.ThenAsync("dovrei vedere \"Employer Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 11
    await testRunner.AndAsync("dovrei vedere \"Admin Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Un cercatore di lavoro visualizza tutte le offerte di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Copertura visualizzazione offerte di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Un cercatore di lavoro visualizza tutte le offerte di lavoro")]
        [global::Xunit.TraitAttribute("Category", "auth:jobseeker")]
        public async global::System.Threading.Tasks.Task UnCercatoreDiLavoroVisualizzaTutteLeOfferteDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:jobseeker"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un cercatore di lavoro visualizza tutte le offerte di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("che sono sulla pagina \"Offerte di lavoro\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 16
    await testRunner.ThenAsync("dovrei vedere \"Employer Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 17
    await testRunner.AndAsync("dovrei vedere \"Admin Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Un datore di lavoro visualizza solo le proprie offerte di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Copertura visualizzazione offerte di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Un datore di lavoro visualizza solo le proprie offerte di lavoro")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task UnDatoreDiLavoroVisualizzaSoloLeProprieOfferteDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un datore di lavoro visualizza solo le proprie offerte di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("che sono sulla pagina \"Offerte di lavoro\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 22
    await testRunner.ThenAsync("dovrei vedere \"Employer Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 23
    await testRunner.AndAsync("non dovrei vedere \"Admin Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Un amministratore visualizza tutte le offerte di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Copertura visualizzazione offerte di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Un amministratore visualizza tutte le offerte di lavoro")]
        [global::Xunit.TraitAttribute("Category", "auth:admin")]
        public async global::System.Threading.Tasks.Task UnAmministratoreVisualizzaTutteLeOfferteDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un amministratore visualizza tutte le offerte di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
    await testRunner.GivenAsync("che sono sulla pagina \"Offerte di lavoro\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 28
    await testRunner.ThenAsync("dovrei vedere \"Employer Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 29
    await testRunner.AndAsync("dovrei vedere \"Admin Seed Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CoperturaVisualizzazioneOfferteDiLavoroFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CoperturaVisualizzazioneOfferteDiLavoroFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
