// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DevSpot.Copilot.AcceptanceTests.Features.Account
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "seed:roles")]
    [global::Xunit.TraitAttribute("Category", "seed:users")]
    public partial class RegistrazioneAccountFeature : object, global::Xunit.IClassFixture<RegistrazioneAccountFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "seed:roles",
                "seed:users"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("it"), "Features/Account", "Registrazione account", "  In qualità di visitatore\n  Voglio creare un account scegliendo il mio ruolo di " +
                "accesso\n  Così da poter usare la piattaforma senza errori", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RegisterAccount.feature"
#line hidden
        
        public RegistrazioneAccountFeature(RegistrazioneAccountFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Account/RegisterAccount.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Un visitatore crea un account come cercatore di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Registrazione account")]
        [global::Xunit.TraitAttribute("Description", "Un visitatore crea un account come cercatore di lavoro")]
        public async global::System.Threading.Tasks.Task UnVisitatoreCreaUnAccountComeCercatoreDiLavoro()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un visitatore crea un account come cercatore di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("che sono sulla pagina \"Registrazione\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table3.AddRow(new string[] {
                            "Input.Email",
                            "seeker.it@devspot.com"});
                table3.AddRow(new string[] {
                            "Input.Password",
                            "JobSeeker123!"});
                table3.AddRow(new string[] {
                            "Input.ConfirmPassword",
                            "JobSeeker123!"});
                table3.AddRow(new string[] {
                            "Input.IsJobSeeker",
                            "true"});
#line 10
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori", ((string)(null)), table3, "Quando ");
#line hidden
#line 16
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Home\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 18
    await testRunner.WhenAsync("seguo il reindirizzamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 19
    await testRunner.ThenAsync("dovrei vedere \"Logout\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 20
    await testRunner.AndAsync("il database dovrebbe contenere un utente con email \"seeker.it@devspot.com\" nel ru" +
                        "olo \"JobSeeker\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Un visitatore crea un account come datore di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Registrazione account")]
        [global::Xunit.TraitAttribute("Description", "Un visitatore crea un account come datore di lavoro")]
        public async global::System.Threading.Tasks.Task UnVisitatoreCreaUnAccountComeDatoreDiLavoro()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un visitatore crea un account come datore di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
    await testRunner.GivenAsync("che sono sulla pagina \"Registrazione\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table4.AddRow(new string[] {
                            "Input.Email",
                            "employer.it@devspot.com"});
                table4.AddRow(new string[] {
                            "Input.Password",
                            "Employer123!"});
                table4.AddRow(new string[] {
                            "Input.ConfirmPassword",
                            "Employer123!"});
                table4.AddRow(new string[] {
                            "Input.IsJobSeeker",
                            "false"});
#line 24
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori", ((string)(null)), table4, "Quando ");
#line hidden
#line 30
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 31
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Home\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 32
    await testRunner.WhenAsync("seguo il reindirizzamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 33
    await testRunner.ThenAsync("dovrei vedere \"Logout\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 34
    await testRunner.AndAsync("il database dovrebbe contenere un utente con email \"employer.it@devspot.com\" nel " +
                        "ruolo \"Employer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Dati non validi di registrazione mostrano gli errori di convalida")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Registrazione account")]
        [global::Xunit.TraitAttribute("Description", "Dati non validi di registrazione mostrano gli errori di convalida")]
        public async global::System.Threading.Tasks.Task DatiNonValidiDiRegistrazioneMostranoGliErroriDiConvalida()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dati non validi di registrazione mostrano gli errori di convalida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("che sono sulla pagina \"Registrazione\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 38
    await testRunner.WhenAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 39
    await testRunner.ThenAsync("dovrei vedere il messaggio di convalida \"Il campo Email è obbligatorio.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 40
    await testRunner.AndAsync("dovrei vedere il messaggio di convalida \"Il campo Password è obbligatorio.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Una password di conferma non corrispondente mostra un errore")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Registrazione account")]
        [global::Xunit.TraitAttribute("Description", "Una password di conferma non corrispondente mostra un errore")]
        public async global::System.Threading.Tasks.Task UnaPasswordDiConfermaNonCorrispondenteMostraUnErrore()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una password di conferma non corrispondente mostra un errore", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
    await testRunner.GivenAsync("che sono sulla pagina \"Registrazione\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table5.AddRow(new string[] {
                            "Input.Email",
                            "mismatch.it@devspot.com"});
                table5.AddRow(new string[] {
                            "Input.Password",
                            "Password123!"});
                table5.AddRow(new string[] {
                            "Input.ConfirmPassword",
                            "Password456!"});
                table5.AddRow(new string[] {
                            "Input.IsJobSeeker",
                            "true"});
#line 44
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori", ((string)(null)), table5, "Quando ");
#line hidden
#line 50
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 51
    await testRunner.ThenAsync("dovrei vedere il messaggio di convalida \"La password e la password di conferma no" +
                        "n corrispondono.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await RegistrazioneAccountFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await RegistrazioneAccountFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
