// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DevSpot.Antigravity.AcceptanceTests.Features.JobPosting
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GestioneDegliAnnunciDiLavoroFeature : object, Xunit.IClassFixture<GestioneDegliAnnunciDiLavoroFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "JobPosting.feature"
#line hidden
        
        public GestioneDegliAnnunciDiLavoroFeature(GestioneDegliAnnunciDiLavoroFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("it"), "Features/JobPosting", "Gestione degli Annunci di Lavoro", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="L\'accesso alla pagina di creazione annuncio come utente anonimo dovrebbe reindiri" +
            "zzare al login")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "L\'accesso alla pagina di creazione annuncio come utente anonimo dovrebbe reindiri" +
            "zzare al login")]
        [Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async System.Threading.Tasks.Task LaccessoAllaPaginaDiCreazioneAnnuncioComeUtenteAnonimoDovrebbeReindirizzareAlLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:anonymous"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("L\'accesso alla pagina di creazione annuncio come utente anonimo dovrebbe reindiri" +
                    "zzare al login", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.WhenAsync("navigo alla pagina \"Create Job Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 7
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina di login", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creazione valida di un annuncio di lavoro da parte di un Datore di Lavoro")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Creazione valida di un annuncio di lavoro da parte di un Datore di Lavoro")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:employer")]
        public async System.Threading.Tasks.Task CreazioneValidaDiUnAnnuncioDiLavoroDaParteDiUnDatoreDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:employer"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creazione valida di un annuncio di lavoro da parte di un Datore di Lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
    await testRunner.GivenAsync("che sono sulla pagina \"Create Job Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table6.AddRow(new string[] {
                            "Title",
                            "Senior C# Architect"});
                table6.AddRow(new string[] {
                            "Description",
                            "We are looking for a senior architect."});
                table6.AddRow(new string[] {
                            "Company",
                            "TechCorp"});
                table6.AddRow(new string[] {
                            "Location",
                            "Remote"});
#line 12
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table6, "Quando ");
#line hidden
#line 18
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 19
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 20
    await testRunner.AndAsync("un annuncio di lavoro con titolo \"Senior C# Architect\" dovrebbe esistere nel sist" +
                        "ema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creazione valida di un annuncio di lavoro da parte di un Amministratore")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Creazione valida di un annuncio di lavoro da parte di un Amministratore")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:admin")]
        public async System.Threading.Tasks.Task CreazioneValidaDiUnAnnuncioDiLavoroDaParteDiUnAmministratore()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:admin"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creazione valida di un annuncio di lavoro da parte di un Amministratore", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("che sono sulla pagina \"Create Job Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table7.AddRow(new string[] {
                            "Title",
                            "Admin Placed Job"});
                table7.AddRow(new string[] {
                            "Description",
                            "This is a job posted by the administrator."});
                table7.AddRow(new string[] {
                            "Company",
                            "DevSpot"});
                table7.AddRow(new string[] {
                            "Location",
                            "Milan"});
#line 25
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table7, "Quando ");
#line hidden
#line 31
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 32
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 33
    await testRunner.AndAsync("un annuncio di lavoro con titolo \"Admin Placed Job\" dovrebbe esistere nel sistema" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creazione non valida di un annuncio di lavoro con descrizione mancante")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Creazione non valida di un annuncio di lavoro con descrizione mancante")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:employer")]
        public async System.Threading.Tasks.Task CreazioneNonValidaDiUnAnnuncioDiLavoroConDescrizioneMancante()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:employer"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creazione non valida di un annuncio di lavoro con descrizione mancante", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("che sono sulla pagina \"Create Job Posting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table8.AddRow(new string[] {
                            "Title",
                            "Missing Description Job"});
                table8.AddRow(new string[] {
                            "Company",
                            "TechCorp"});
                table8.AddRow(new string[] {
                            "Location",
                            "Remote"});
#line 38
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table8, "Quando ");
#line hidden
#line 43
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 44
    await testRunner.ThenAsync("dovrei vedere degli errori di validazione", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visualizzazione annunci come utente anonimo")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Visualizzazione annunci come utente anonimo")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async System.Threading.Tasks.Task VisualizzazioneAnnunciComeUtenteAnonimo()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:anonymous"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizzazione annunci come utente anonimo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
    await testRunner.GivenAsync("che esiste un annuncio di lavoro con titolo \"Developer Anonimo\" inserito da \"admi" +
                        "n@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 49
    await testRunner.AndAsync("esiste un annuncio di lavoro con titolo \"Developer Azienda\" inserito da \"employer" +
                        "@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 50
    await testRunner.WhenAsync("navigo alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 51
    await testRunner.ThenAsync("dovrei vedere l\'annuncio con titolo \"Developer Anonimo\" nella pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 52
    await testRunner.AndAsync("dovrei vedere l\'annuncio con titolo \"Developer Azienda\" nella pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visualizzazione annunci come amministratore")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Visualizzazione annunci come amministratore")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:admin")]
        public async System.Threading.Tasks.Task VisualizzazioneAnnunciComeAmministratore()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:admin"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizzazione annunci come amministratore", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
    await testRunner.GivenAsync("che esiste un annuncio di lavoro con titolo \"Developer Anonimo\" inserito da \"admi" +
                        "n@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 57
    await testRunner.AndAsync("esiste un annuncio di lavoro con titolo \"Developer Azienda\" inserito da \"employer" +
                        "@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 58
    await testRunner.WhenAsync("navigo alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 59
    await testRunner.ThenAsync("dovrei vedere l\'annuncio con titolo \"Developer Anonimo\" nella pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 60
    await testRunner.AndAsync("dovrei vedere l\'annuncio con titolo \"Developer Azienda\" nella pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visualizzazione annunci come datore di lavoro mostra solo i propri annunci")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Visualizzazione annunci come datore di lavoro mostra solo i propri annunci")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:employer")]
        public async System.Threading.Tasks.Task VisualizzazioneAnnunciComeDatoreDiLavoroMostraSoloIPropriAnnunci()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:employer"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizzazione annunci come datore di lavoro mostra solo i propri annunci", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 64
    await testRunner.GivenAsync("che esiste un annuncio di lavoro con titolo \"Developer Anonimo\" inserito da \"admi" +
                        "n@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 65
    await testRunner.AndAsync("esiste un annuncio di lavoro con titolo \"Developer Azienda\" inserito da \"employer" +
                        "@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 66
    await testRunner.WhenAsync("navigo alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 67
    await testRunner.ThenAsync("dovrei vedere l\'annuncio con titolo \"Developer Azienda\" nella pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 68
    await testRunner.AndAsync("non dovrei vedere l\'annuncio con titolo \"Developer Anonimo\" nella pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancellazione annuncio come amministratore")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Cancellazione annuncio come amministratore")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:admin")]
        public async System.Threading.Tasks.Task CancellazioneAnnuncioComeAmministratore()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:admin"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancellazione annuncio come amministratore", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
    await testRunner.GivenAsync("che esiste un annuncio di lavoro con titolo \"Job da Eliminare Admin\" inserito da " +
                        "\"employer@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 73
    await testRunner.WhenAsync("elimino l\'annuncio con titolo \"Job da Eliminare Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 74
    await testRunner.ThenAsync("dovrei ottenere uno stato di risposta \"OK\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 75
    await testRunner.AndAsync("un annuncio di lavoro con titolo \"Job da Eliminare Admin\" non dovrebbe esistere n" +
                        "el sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancellazione del proprio annuncio come datore di lavoro")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione degli Annunci di Lavoro")]
        [Xunit.TraitAttribute("Description", "Cancellazione del proprio annuncio come datore di lavoro")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:employer")]
        public async System.Threading.Tasks.Task CancellazioneDelProprioAnnuncioComeDatoreDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:employer"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancellazione del proprio annuncio come datore di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 79
    await testRunner.GivenAsync("che esiste un annuncio di lavoro con titolo \"Mio Job Datore\" inserito da \"employe" +
                        "r@devspot.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 80
    await testRunner.WhenAsync("elimino l\'annuncio con titolo \"Mio Job Datore\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 81
    await testRunner.ThenAsync("dovrei ottenere uno stato di risposta \"OK\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 82
    await testRunner.AndAsync("un annuncio di lavoro con titolo \"Mio Job Datore\" non dovrebbe esistere nel siste" +
                        "ma", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GestioneDegliAnnunciDiLavoroFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GestioneDegliAnnunciDiLavoroFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
