// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DevSpot.Claude.AcceptanceTests.Features.JobPosting
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreazioneDiUnAnnuncioDiLavoroFeature : object, global::Xunit.IClassFixture<CreazioneDiUnAnnuncioDiLavoroFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("it"), "Features/JobPosting", "Creazione di un annuncio di lavoro", "  Come datore di lavoro o amministratore\n  Voglio creare annunci di lavoro\n  In m" +
                "odo che i candidati possano trovare opportunità di lavoro", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateJobPosting.feature"
#line hidden
        
        public CreazioneDiUnAnnuncioDiLavoroFeature(CreazioneDiUnAnnuncioDiLavoroFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/JobPosting/CreateJobPosting.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Il datore di lavoro crea un annuncio valido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Creazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Il datore di lavoro crea un annuncio valido")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task IlDatoreDiLavoroCreaUnAnnuncioValido()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Il datore di lavoro crea un annuncio valido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("sono sulla pagina del modulo \"/JobPostings/Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table3.AddRow(new string[] {
                            "Title",
                            ".NET Developer"});
                table3.AddRow(new string[] {
                            "Description",
                            "Looking for a .NET dev"});
                table3.AddRow(new string[] {
                            "Company",
                            "Acme Srl"});
                table3.AddRow(new string[] {
                            "Location",
                            "Udine"});
#line 9
    await testRunner.WhenAsync("compilo il modulo con i seguenti dati", ((string)(null)), table3, "Quando ");
#line hidden
#line 15
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 16
    await testRunner.ThenAsync("vengo reindirizzato a \"/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 17
    await testRunner.AndAsync("l\'annuncio \".NET Developer\" viene salvato nel database", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Il datore di lavoro non può creare un annuncio senza titolo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Creazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Il datore di lavoro non può creare un annuncio senza titolo")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task IlDatoreDiLavoroNonPuoCreareUnAnnuncioSenzaTitolo()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Il datore di lavoro non può creare un annuncio senza titolo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("sono sulla pagina del modulo \"/JobPostings/Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table4.AddRow(new string[] {
                            "Title",
                            ""});
                table4.AddRow(new string[] {
                            "Description",
                            "Missing title scenario"});
                table4.AddRow(new string[] {
                            "Company",
                            "Acme Srl"});
                table4.AddRow(new string[] {
                            "Location",
                            "Udine"});
#line 22
    await testRunner.WhenAsync("compilo il modulo con i seguenti dati", ((string)(null)), table4, "Quando ");
#line hidden
#line 28
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 29
    await testRunner.ThenAsync("vedo un errore di validazione per il campo \"Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 30
    await testRunner.AndAsync("nessun annuncio \"Missing title scenario\" viene salvato nel database", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Il datore di lavoro non può creare un annuncio senza descrizione")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Creazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Il datore di lavoro non può creare un annuncio senza descrizione")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task IlDatoreDiLavoroNonPuoCreareUnAnnuncioSenzaDescrizione()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Il datore di lavoro non può creare un annuncio senza descrizione", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("sono sulla pagina del modulo \"/JobPostings/Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table5.AddRow(new string[] {
                            "Title",
                            "Dev Job No Description"});
                table5.AddRow(new string[] {
                            "Description",
                            ""});
                table5.AddRow(new string[] {
                            "Company",
                            "Acme Srl"});
                table5.AddRow(new string[] {
                            "Location",
                            "Udine"});
#line 35
    await testRunner.WhenAsync("compilo il modulo con i seguenti dati", ((string)(null)), table5, "Quando ");
#line hidden
#line 41
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 42
    await testRunner.ThenAsync("vedo un errore di validazione per il campo \"Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Il datore di lavoro non può creare un annuncio senza azienda")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Creazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Il datore di lavoro non può creare un annuncio senza azienda")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task IlDatoreDiLavoroNonPuoCreareUnAnnuncioSenzaAzienda()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Il datore di lavoro non può creare un annuncio senza azienda", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
    await testRunner.GivenAsync("sono sulla pagina del modulo \"/JobPostings/Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table6.AddRow(new string[] {
                            "Title",
                            "Dev Job No Company"});
                table6.AddRow(new string[] {
                            "Description",
                            "Some description"});
                table6.AddRow(new string[] {
                            "Company",
                            ""});
                table6.AddRow(new string[] {
                            "Location",
                            "Udine"});
#line 47
    await testRunner.WhenAsync("compilo il modulo con i seguenti dati", ((string)(null)), table6, "Quando ");
#line hidden
#line 53
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 54
    await testRunner.ThenAsync("vedo un errore di validazione per il campo \"Company\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="L\'utente anonimo viene reindirizzato al login quando accede alla pagina di creazi" +
            "one")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Creazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "L\'utente anonimo viene reindirizzato al login quando accede alla pagina di creazi" +
            "one")]
        public async global::System.Threading.Tasks.Task LutenteAnonimoVieneReindirizzatoAlLoginQuandoAccedeAllaPaginaDiCreazione()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("L\'utente anonimo viene reindirizzato al login quando accede alla pagina di creazi" +
                    "one", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.WhenAsync("visito la pagina \"/JobPostings/Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 58
    await testRunner.ThenAsync("vengo reindirizzato alla pagina di accesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="L\'amministratore crea un annuncio valido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Creazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "L\'amministratore crea un annuncio valido")]
        [global::Xunit.TraitAttribute("Category", "auth:admin")]
        public async global::System.Threading.Tasks.Task LamministratoreCreaUnAnnuncioValido()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("L\'amministratore crea un annuncio valido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 62
    await testRunner.GivenAsync("sono sulla pagina del modulo \"/JobPostings/Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valore"});
                table7.AddRow(new string[] {
                            "Title",
                            "Admin Job Posting"});
                table7.AddRow(new string[] {
                            "Description",
                            "Created by admin"});
                table7.AddRow(new string[] {
                            "Company",
                            "DevSpot HQ"});
                table7.AddRow(new string[] {
                            "Location",
                            "Remote"});
#line 63
    await testRunner.WhenAsync("compilo il modulo con i seguenti dati", ((string)(null)), table7, "Quando ");
#line hidden
#line 69
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 70
    await testRunner.ThenAsync("vengo reindirizzato a \"/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 71
    await testRunner.AndAsync("l\'annuncio \"Admin Job Posting\" viene salvato nel database", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreazioneDiUnAnnuncioDiLavoroFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreazioneDiUnAnnuncioDiLavoroFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
