// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DevSpot.Claude.AcceptanceTests.Features.JobPosting
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CancellazioneDiUnAnnuncioDiLavoroFeature : object, global::Xunit.IClassFixture<CancellazioneDiUnAnnuncioDiLavoroFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("it"), "Features/JobPosting", "Cancellazione di un annuncio di lavoro", "  Come utente autorizzato\n  Voglio poter cancellare gli annunci di lavoro\n  In mo" +
                "do da gestire correttamente le offerte presenti sulla piattaforma", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DeleteJobPosting.feature"
#line hidden
        
        public CancellazioneDiUnAnnuncioDiLavoroFeature(CancellazioneDiUnAnnuncioDiLavoroFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/JobPosting/DeleteJobPosting.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Il datore di lavoro cancella il proprio annuncio")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cancellazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Il datore di lavoro cancella il proprio annuncio")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task IlDatoreDiLavoroCancellaIlProprioAnnuncio()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Il datore di lavoro cancella il proprio annuncio", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("nel database esiste un annuncio con titolo \"Annuncio da Cancellare\" dell\'utente \"" +
                        "employer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 9
    await testRunner.WhenAsync("invio la richiesta di cancellazione per l\'annuncio \"Annuncio da Cancellare\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("l\'annuncio \"Annuncio da Cancellare\" non è più presente nel database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="L\'amministratore cancella l\'annuncio di un datore di lavoro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cancellazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "L\'amministratore cancella l\'annuncio di un datore di lavoro")]
        [global::Xunit.TraitAttribute("Category", "auth:admin")]
        public async global::System.Threading.Tasks.Task LamministratoreCancellaLannuncioDiUnDatoreDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("L\'amministratore cancella l\'annuncio di un datore di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("nel database esiste un annuncio con titolo \"Annuncio del Datore\" dell\'utente \"emp" +
                        "loyer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 15
    await testRunner.WhenAsync("invio la richiesta di cancellazione per l\'annuncio \"Annuncio del Datore\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.ThenAsync("l\'annuncio \"Annuncio del Datore\" non è più presente nel database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Il datore di lavoro non può cancellare l\'annuncio di un altro utente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cancellazione di un annuncio di lavoro")]
        [global::Xunit.TraitAttribute("Description", "Il datore di lavoro non può cancellare l\'annuncio di un altro utente")]
        [global::Xunit.TraitAttribute("Category", "auth:employer")]
        public async global::System.Threading.Tasks.Task IlDatoreDiLavoroNonPuoCancellareLannuncioDiUnAltroUtente()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:employer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Il datore di lavoro non può cancellare l\'annuncio di un altro utente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("nel database esiste un annuncio con titolo \"Annuncio dell\'Admin\" dell\'utente \"adm" +
                        "in\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
#line 21
    await testRunner.WhenAsync("invio la richiesta di cancellazione per l\'annuncio \"Annuncio dell\'Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("ricevo una risposta di accesso negato", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CancellazioneDiUnAnnuncioDiLavoroFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CancellazioneDiUnAnnuncioDiLavoroFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
