// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DevSpot.Antigravity.AcceptanceTests.Features.Account
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GestioneDellAccountFeature : object, Xunit.IClassFixture<GestioneDellAccountFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Account.feature"
#line hidden
        
        public GestioneDellAccountFeature(GestioneDellAccountFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("it"), "Features/Account", "Gestione dell\'Account", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrazione valida come cercatore di lavoro")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione dell\'Account")]
        [Xunit.TraitAttribute("Description", "Registrazione valida come cercatore di lavoro")]
        [Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async System.Threading.Tasks.Task RegistrazioneValidaComeCercatoreDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:anonymous"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrazione valida come cercatore di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync("che sono sulla pagina \"Register\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "Email",
                            "seeker@test.com"});
                table1.AddRow(new string[] {
                            "Password",
                            "Password123!"});
                table1.AddRow(new string[] {
                            "ConfirmPassword",
                            "Password123!"});
                table1.AddRow(new string[] {
                            "IsJobSeeker",
                            "true"});
#line 7
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table1, "Quando ");
#line hidden
#line 13
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 14
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 15
    await testRunner.AndAsync("un utente con email \"seeker@test.com\" dovrebbe esistere", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 16
    await testRunner.AndAsync("l\'utente \"seeker@test.com\" dovrebbe avere il ruolo \"JobSeeker\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrazione valida come datore di lavoro")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione dell\'Account")]
        [Xunit.TraitAttribute("Description", "Registrazione valida come datore di lavoro")]
        [Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async System.Threading.Tasks.Task RegistrazioneValidaComeDatoreDiLavoro()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:anonymous"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrazione valida come datore di lavoro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("che sono sulla pagina \"Register\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "Email",
                            "employer_reg@test.com"});
                table2.AddRow(new string[] {
                            "Password",
                            "Password123!"});
                table2.AddRow(new string[] {
                            "ConfirmPassword",
                            "Password123!"});
                table2.AddRow(new string[] {
                            "IsJobSeeker",
                            "false"});
#line 21
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table2, "Quando ");
#line hidden
#line 27
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 28
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
#line 29
    await testRunner.AndAsync("un utente con email \"employer_reg@test.com\" dovrebbe esistere", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 30
    await testRunner.AndAsync("l\'utente \"employer_reg@test.com\" dovrebbe avere il ruolo \"Employer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Registrazione non valida con password non corrispondente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione dell\'Account")]
        [Xunit.TraitAttribute("Description", "Registrazione non valida con password non corrispondente")]
        [Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async System.Threading.Tasks.Task RegistrazioneNonValidaConPasswordNonCorrispondente()
        {
            string[] tagsOfScenario = new string[] {
                    "auth:anonymous"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrazione non valida con password non corrispondente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("che sono sulla pagina \"Register\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table3.AddRow(new string[] {
                            "Email",
                            "bad@test.com"});
                table3.AddRow(new string[] {
                            "Password",
                            "Password123!"});
                table3.AddRow(new string[] {
                            "ConfirmPassword",
                            "Mismatch123!"});
#line 35
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table3, "Quando ");
#line hidden
#line 40
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 41
    await testRunner.ThenAsync("dovrei vedere degli errori di validazione", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Accesso con credenziali valide")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione dell\'Account")]
        [Xunit.TraitAttribute("Description", "Accesso con credenziali valide")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async System.Threading.Tasks.Task AccessoConCredenzialiValide()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:anonymous"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Accesso con credenziali valide", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("che sono sulla pagina \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table4.AddRow(new string[] {
                            "Email",
                            "admin@devspot.com"});
                table4.AddRow(new string[] {
                            "Password",
                            "Admin123!"});
#line 46
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table4, "Quando ");
#line hidden
#line 50
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 51
    await testRunner.ThenAsync("dovrei essere reindirizzato alla pagina \"Job Postings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Accesso fallito con credenziali non valide")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestione dell\'Account")]
        [Xunit.TraitAttribute("Description", "Accesso fallito con credenziali non valide")]
        [Xunit.TraitAttribute("Category", "seed:users")]
        [Xunit.TraitAttribute("Category", "auth:anonymous")]
        public async System.Threading.Tasks.Task AccessoFallitoConCredenzialiNonValide()
        {
            string[] tagsOfScenario = new string[] {
                    "seed:users",
                    "auth:anonymous"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Accesso fallito con credenziali non valide", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("che sono sulla pagina \"Login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dato ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table5.AddRow(new string[] {
                            "Email",
                            "admin@devspot.com"});
                table5.AddRow(new string[] {
                            "Password",
                            "PasswordErrata1!"});
#line 56
    await testRunner.WhenAsync("compilo il modulo con i seguenti valori:", ((string)(null)), table5, "Quando ");
#line hidden
#line 60
    await testRunner.AndAsync("invio il modulo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 61
    await testRunner.ThenAsync("dovrei vedere il messaggio di errore di validazione \"Invalid login attempt.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Allora ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GestioneDellAccountFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GestioneDellAccountFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
